### Variables
//@baseUrl = http://localhost:8081/test
@baseUrl = http://localhost:8081/esiag_proto

### 1. Récupérer le chemin (findChemin)
GET {{baseUrl}}/
Accept: application/json

###

### 2. Récupérer le parcours d'un patient par son ID (findParcours)
# Remplacez 123 par un ID existant
GET {{baseUrl}}/1
Accept: application/json

###

### 3. Récupérer tous les actes médicaux (findActeMedicals)
GET {{baseUrl}}/all
Accept: application/json

###

### 4. Récupérer le parcours patient spécifique (findActeMedicalById)
GET {{baseUrl}}/parcourspatient/1
Accept: application/json

### 5. Récupérer le statut des parcours pour tous les patients (findAllPatientStatutParcours)
GET http://localhost:8081/api/parcours/all
Accept: application/json

### 6. Récupérer le statut du parcours pour un patient spécifique (findPatientStatutParcoursById)
GET http://localhost:8081/api/parcours/1
Accept: application/json

####################################################

### Voir la file d'attente
GET http://localhost:8081/api/file-attente


### 7. Commencer un parcours pour un patient (commencerParcours)


### 8. Récupérer le chemin entre deux espaces (findCheminSalle)
GET http://localhost:8081/api/parcours/chemin/5/10/3
Accept: application/json
